version: '3.5'

services:

  django:
    build:
      context: .
      dockerfile: ./contrib/dev/Dockerfile
    image: b2b_django
    depends_on:
        - db
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .envs/db

  db:
    hostname: db
    image: kartoza/postgis
    restart: always
    env_file:
      - .envs/db